USE [master]
GO

/****** Object:  Database [ClothesDB]    Script Date: 10/17/2016 1:30:10 PM ******/
CREATE DATABASE [ClothesDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClothesDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ClothesDB.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ClothesDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\ClothesDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ClothesDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClothesDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ClothesDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ClothesDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ClothesDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ClothesDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ClothesDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ClothesDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ClothesDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ClothesDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ClothesDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ClothesDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ClothesDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ClothesDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ClothesDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ClothesDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ClothesDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ClothesDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ClothesDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ClothesDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ClothesDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ClothesDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ClothesDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ClothesDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ClothesDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ClothesDB] SET  MULTI_USER 
GO

ALTER DATABASE [ClothesDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ClothesDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ClothesDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ClothesDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ClothesDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ClothesDB] SET  READ_WRITE 
GO

